version: '3.8'


services:
  db:
    image: postgres:alpine
    container_name: stock_dashboard_psql_db
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
      - ./db/stock_dashboard/schema:/docker-entrypoint-initdb.d/schema
      - ./db/stock_dashboard/CREATE_DB.sql:/docker-entrypoint-initdb.d/CREATE_DB.sql
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - .env
    logging:
      driver: none
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  rmq:
    image: rabbitmq:3-management
    command: rabbitmq-server
    container_name: stock_dashboard_rmq
    env_file:
      - .env
    environment:
      RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE}"
    volumes:
      - ./rmq_data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    logging:
      driver: none
    restart: always

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: stock_dashboard_api
    depends_on:
      db:
        condition: service_healthy
      rmq:
        condition: service_started
    links:
      - db
      - rmq
    env_file:
      - .env
    ports:
      - 5000:5000
    command: flask run --host=0.0.0.0 --port=5000
    restart: always
